/*
 * File: app/store/GoogleFitStore.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('HealthTracker.store.GoogleFitStore', {
    extend: 'Ext.data.Store',

    requires: [
        'Ext.data.proxy.Ajax',
        'Ext.data.reader.Json',
        'Ext.data.Field'
    ],

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            itemId: 'GoogleFitStore',
            storeId: 'GoogleFitStore',
            data: [
                {
                    date: '2017-07-15T09:54:14.024Z',
                    calories: 594,
                    steps: 704
                },
                {
                    date: '2017-04-08T21:50:29.024Z',
                    calories: 976,
                    steps: 360
                },
                {
                    date: '2017-07-06T06:35:05.024Z',
                    calories: 315,
                    steps: 684
                },
                {
                    date: '2017-04-08T16:16:19.024Z',
                    calories: 747,
                    steps: 180
                },
                {
                    date: '2017-04-06T09:20:18.024Z',
                    calories: 251,
                    steps: 260
                }
            ],
            proxy: {
                type: 'ajax',
                url: 'data/activitydata.json',
                reader: {
                    type: 'json'
                }
            },
            fields: [
                {
                    name: 'date',
                    type: 'date'
                },
                {
                    name: 'calories',
                    type: 'int'
                },
                {
                    name: 'steps',
                    type: 'int'
                }
            ]
        }, cfg)]);
    }
});