/*
 * File: app/store/VitalsStore.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('HealthTracker.store.VitalsStore', {
    extend: 'Ext.data.Store',

    requires: [
        'HealthTracker.model.Vitals',
        'Ext.data.proxy.Ajax',
        'Ext.data.reader.Xml',
        'Ext.data.Field',
        'Ext.util.Sorter'
    ],

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            autoLoad: true,
            model: 'HealthTracker.model.Vitals',
            storeId: 'VitalsStore',
            proxy: {
                type: 'ajax',
                url: 'data/vitalsfull.xml',
                reader: {
                    type: 'xml',
                    root: 'PatientVitals',
                    record: 'VitalRecord'
                }
            },
            fields: [
                {
                    name: 'visitDate'
                },
                {
                    name: 'weight'
                },
                {
                    name: 'vitaminB12'
                },
                {
                    name: 'triglycerides'
                },
                {
                    name: 'vitaminD'
                }
            ],
            sorters: {
                property: 'visitDate'
            }
        }, cfg)]);
    }
});