/*
 * File: app/view/MainView.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('HealthTracker.view.MainView', {
    extend: 'Ext.container.Viewport',

    requires: [
        'Ext.grid.Panel',
        'Ext.grid.column.Date',
        'Ext.grid.column.Number',
        'Ext.form.CheckboxGroup',
        'Ext.form.Panel',
        'Ext.chart.Chart',
        'Ext.chart.axis.Time',
        'Ext.chart.Legend',
        'Ext.chart.series.Column'
    ],

    itemId: 'mainView',
    layout: 'border',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'panel',
                    flex: 1,
                    region: 'west',
                    split: true,
                    itemId: 'leftPanel',
                    width: 150,
                    layout: 'fit',
                    collapseDirection: 'left',
                    collapsible: true,
                    title: 'Vitals Data',
                    items: [
                        {
                            xtype: 'gridpanel',
                            itemId: 'mygridpanel3',
                            autoScroll: true,
                            store: 'VitalsStore',
                            columns: [
                                {
                                    xtype: 'datecolumn',
                                    sortable: true,
                                    dataIndex: 'visitDate',
                                    text: 'VisitDate'
                                },
                                {
                                    xtype: 'numbercolumn',
                                    dataIndex: 'weight',
                                    text: 'Weight'
                                },
                                {
                                    xtype: 'numbercolumn',
                                    dataIndex: 'vitaminB12',
                                    text: 'VitaminB12'
                                },
                                {
                                    xtype: 'numbercolumn',
                                    dataIndex: 'triglycerides',
                                    text: 'Triglycerides'
                                },
                                {
                                    xtype: 'numbercolumn',
                                    dataIndex: 'vitaminD',
                                    text: 'VitaminD'
                                }
                            ]
                        }
                    ]
                },
                {
                    xtype: 'panel',
                    region: 'center',
                    itemId: 'middlePanel',
                    collapseDirection: 'left',
                    collapsed: true,
                    collapsible: true,
                    title: 'Vitals Chart'
                },
                {
                    xtype: 'panel',
                    flex: 1,
                    region: 'east',
                    split: true,
                    itemId: 'rightPanel',
                    width: 150,
                    bodyPadding: 5,
                    collapseDirection: 'right',
                    collapsible: true,
                    title: 'Vitals Chart Builder',
                    items: [
                        {
                            xtype: 'checkboxgroup',
                            border: 1,
                            id: 'selectionGroup',
                            width: 400,
                            fieldLabel: '',
                            columns: 'auto'
                        },
                        {
                            xtype: 'form',
                            toggleChartSeries: function(checked, checkbox) {
                                // Get the chart to update
                                var chart = Ext.getCmp("vitalsLineChart");


                                var checkboxId = checkbox.id;
                                var seriesName = checkboxId.concat('Series');


                                if ( checked ) {
                                    //create a series for the selected checkbox
                                    var series = {
                                        type: 'line',
                                        itemId: seriesName,
                                        id: seriesName,
                                        seriesId: seriesName,
                                        axis: 'left',
                                        xField: 'visitDate',
                                        yField: checkboxId
                                    };

                                    // add the series
                                    chart.series.add( series );
                                }
                                else {
                                    var series = chart.series.getByKey(seriesName);

                                    // remove the series
                                    //series.clear();
                                    chart.series.remove(series);
                                }

                                // redraw the chart
                                //chart.surface.removeAll();
                                chart.redraw(false);
                            },
                            id: 'vitalsForm',
                            itemId: 'vitalsForm',
                            bodyPadding: 10,
                            layout: {
                                type: 'vbox',
                                align: 'stretch'
                            },
                            items: [
                                {
                                    xtype: 'chart',
                                    height: 250,
                                    id: 'vitalsLineChart',
                                    width: 400,
                                    animate: true,
                                    insetPadding: 20,
                                    store: 'VitalsStore',
                                    axes: [
                                        {
                                            type: 'Time',
                                            fields: [
                                                'visitDate'
                                            ],
                                            majorTickSteps: 10,
                                            position: 'bottom',
                                            title: 'Visited Date',
                                            adjustMaximumByMajorUnit: true,
                                            adjustMinimumByMajorUnit: true,
                                            dateFormat: 'm/d/y',
                                            fromDate: 'Fri Mar 30 2012 00:00:00 GMT-0400 (Eastern Daylight Time)',
                                            step: [
                                                Ext.Date.YEAR,
                                                1
                                            ],
                                            toDate: 'Sun Dec 11 2016 00:00:00 GMT-0500 (Eastern Standard Time)'
                                        },
                                        {
                                            type: 'Numeric',
                                            title: 'Vitals Data',
                                            position: 'left'
                                        }
                                    ],
                                    legend: {
                                        itemId: 'vitalsLegend',
                                        position: 'right'
                                    }
                                },
                                {
                                    xtype: 'chart',
                                    height: 250,
                                    id: 'activityColumnChart',
                                    width: 400,
                                    animate: true,
                                    insetPadding: 20,
                                    store: 'GoogleFitStore',
                                    axes: [
                                        {
                                            type: 'Time',
                                            fields: [
                                                'date'
                                            ],
                                            majorTickSteps: 10,
                                            position: 'bottom',
                                            title: 'Date',
                                            dateFormat: 'm/y',
                                            fromDate: 'Fri Jan 01 2016 00:00:00 GMT-0500 (Eastern Standard Time)',
                                            step: [
                                                Ext.Date.YEAR,
                                                1
                                            ],
                                            toDate: 'Sat Dec 31 2016 00:00:00 GMT-0500 (Eastern Standard Time)'
                                        },
                                        {
                                            type: 'Numeric',
                                            fields: [
                                                'steps'
                                            ],
                                            title: 'Steps',
                                            position: 'left'
                                        }
                                    ],
                                    series: [
                                        {
                                            type: 'column',
                                            label: {
                                                display: 'insideEnd',
                                                field: 'y',
                                                color: '#333',
                                                'text-anchor': 'middle'
                                            },
                                            xField: 'date',
                                            yField: 'steps'
                                        }
                                    ]
                                }
                            ]
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});