/*
 * File: app/view/MainView.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('HealthTracker.view.MainView', {
    extend: 'Ext.container.Viewport',

    requires: [
        'Ext.grid.Panel',
        'Ext.grid.column.Date',
        'Ext.grid.column.Number',
        'Ext.form.Panel',
        'Ext.chart.Chart',
        'Ext.chart.axis.Time',
        'Ext.chart.series.Line',
        'Ext.chart.Legend'
    ],

    itemId: 'mainView',
    layout: 'border',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'panel',
                    flex: 1,
                    region: 'west',
                    split: true,
                    itemId: 'leftPanel',
                    width: 150,
                    layout: 'fit',
                    collapseDirection: 'left',
                    collapsible: true,
                    title: 'Vitals Data',
                    items: [
                        {
                            xtype: 'gridpanel',
                            itemId: 'mygridpanel3',
                            autoScroll: true,
                            store: 'VitalsStore',
                            columns: [
                                {
                                    xtype: 'datecolumn',
                                    sortable: true,
                                    dataIndex: 'visitDate',
                                    text: 'VisitDate'
                                },
                                {
                                    xtype: 'numbercolumn',
                                    dataIndex: 'weight',
                                    text: 'Weight'
                                },
                                {
                                    xtype: 'numbercolumn',
                                    dataIndex: 'vitaminB12',
                                    text: 'VitaminB12'
                                },
                                {
                                    xtype: 'numbercolumn',
                                    dataIndex: 'triglycerides',
                                    text: 'Triglycerides'
                                },
                                {
                                    xtype: 'numbercolumn',
                                    dataIndex: 'vitaminD',
                                    text: 'VitaminD'
                                }
                            ]
                        }
                    ]
                },
                {
                    xtype: 'panel',
                    flex: 1,
                    region: 'center',
                    split: true,
                    itemId: 'rightPanel',
                    bodyPadding: 5,
                    collapseDirection: 'right',
                    collapsible: true,
                    title: 'Vitals Chart',
                    items: [
                        {
                            xtype: 'form',
                            itemId: 'vitalsForm',
                            bodyPadding: 10,
                            layout: {
                                type: 'vbox',
                                align: 'stretch'
                            },
                            items: [
                                {
                                    xtype: 'chart',
                                    height: 250,
                                    width: 400,
                                    animate: true,
                                    insetPadding: 20,
                                    store: 'VitalsStore',
                                    axes: [
                                        {
                                            type: 'Time',
                                            fields: [
                                                'visitDate'
                                            ],
                                            position: 'bottom',
                                            title: 'Visited Date',
                                            adjustMaximumByMajorUnit: true,
                                            adjustMinimumByMajorUnit: true,
                                            dateFormat: 'm/d/y',
                                            step: [
                                                'd',
                                                1
                                            ]
                                        },
                                        {
                                            type: 'Numeric',
                                            fields: [
                                                'weight',
                                                'vitaminB12',
                                                'triglycerides',
                                                'vitaminD'
                                            ],
                                            title: 'Vitals Data',
                                            position: 'left'
                                        }
                                    ],
                                    series: [
                                        {
                                            type: 'line',
                                            itemId: 'weightSeries',
                                            axis: 'left',
                                            xField: 'visitDate',
                                            yField: 'weight',
                                            smooth: 3
                                        },
                                        {
                                            type: 'line',
                                            itemId: 'b12Series',
                                            axis: 'left',
                                            xField: 'visitDate',
                                            yField: 'vitaminB12',
                                            smooth: 3
                                        },
                                        {
                                            type: 'line',
                                            itemId: 'triglyceridesSeries',
                                            axis: 'left',
                                            xField: 'visitDate',
                                            yField: 'triglycerides',
                                            smooth: 3
                                        },
                                        {
                                            type: 'line',
                                            itemId: 'vitaminDSeries',
                                            axis: 'left',
                                            xField: 'visitDate',
                                            yField: 'vitaminD',
                                            smooth: 3
                                        }
                                    ],
                                    legend: {
                                        itemId: 'vitalsLegend',
                                        position: 'right'
                                    }
                                }
                            ]
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});