/*
 * File: app/controller/ChartBuilderFormController.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('HealthTracker.controller.ChartBuilderFormController', {
    extend: 'Ext.app.Controller',

    onCheckboxfieldChange: function(field, newValue, oldValue, eOpts) {
        // Assume one form by that name
        var vitalsForm = Ext.ComponentQuery.query('#vitalsForm')[0];

        vitalsForm.toggleChartSeries( newValue, field );
    },

    onSelectionGroupBeforeRender: function(component, eOpts) {
        // Query the Chart Element Store to determine which options are available
        // The store is set to auto load so no need to load manually
        var chartElementStore = Ext.data.StoreManager.lookup('ChartElementStore');

        var chartElementArray = chartElementStore.data;

        for ( i=0; i<chartElementArray.length; ++i ) {

            chartElementID = chartElementArray.items[i].data.id;
            chartElementName = chartElementArray.items[i].data.name;

            // Add the check box
            var checkboxfield = new Ext.form.field.Checkbox (
                {
                    xtype: 'checkboxfield',
                    id: chartElementID,
                    boxLabel: chartElementName
                }
            );

            component.add( checkboxfield );

        }
    },

    init: function(application) {
        this.control({
            "checkboxfield": {
                change: this.onCheckboxfieldChange
            },
            "#selectionGroup": {
                beforerender: this.onSelectionGroupBeforeRender
            }
        });
    }

});
